name: alert-tuning-tool
channels:
    - conda-forge

dependencies:
    - python=3.7
    - pip
    - sphinx
    - sphinx_rtd_theme
    - sphinx-automodapi
    - nbsphinx
    - numpy
    - pandas
    - scipy

pip:
  - numpydoc
  - ipython